12 
    de.renew.gui.CPNDrawing 101 
        de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1 80 70 24 24 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 2 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 115 70 "p_Submitted" "SansSerif" 1 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator 59 -4 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 3 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 -194 92 "[\"did:example:issuer1\",\"did:example:student1\",\"credential-001\",\"issuer-signature\",\"did:example:student1\",\"vp-001\"]" "SansSerif" 0 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator 26 18 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 4 80 420 24 24 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 5 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 115 420 "p_UnderReview" "SansSerif" 1 12 0 REF 8 
            CH.ifa.draw.standard.OffsetLocator 67 -4 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 6 80 770 24 24 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 7 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 115 770 "p_Validated" "SansSerif" 1 12 0 REF 12 
            CH.ifa.draw.standard.OffsetLocator 56 -4 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 8 80 1120 24 24 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 115 1120 "p_PendingAccept" "SansSerif" 1 12 0 REF 16 
            CH.ifa.draw.standard.OffsetLocator 73 -4 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 10 80 1470 24 24 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 11 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 115 1470 "p_BlockchainAnchored" "SansSerif" 1 12 0 REF 20 
            CH.ifa.draw.standard.OffsetLocator 89 -4 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 12 80 1820 24 24 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 115 1820 "p_ProfileAggregated" "SansSerif" 1 12 0 REF 24 
            CH.ifa.draw.standard.OffsetLocator 81 -4 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 14 1080 1470 24 24 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 15 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1115 1470 "p_Terminated" "SansSerif" 1 12 0 REF 28 
            CH.ifa.draw.standard.OffsetLocator 62 -4 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 16 80 245 24 24 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 17 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 115 245 "t_Review_Init" "SansSerif" 1 12 0 REF 32 
            CH.ifa.draw.standard.OffsetLocator 61 -4 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 18 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 115 267 ":submit(s,w,l,h,grade,passing_threshold,currentTime,expiryDate);\nco :new CredentialObject;\nco:evaluate(grade,passing_threshold,currentTime,expiryDate)" "SansSerif" 0 12 0 REF 32 
            CH.ifa.draw.standard.OffsetLocator 202 34 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 19 80 595 24 24 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 20 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 115 595 "t_Verification_Pass" "SansSerif" 1 12 0 REF 39 
            CH.ifa.draw.standard.OffsetLocator 79 -4 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 21 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 115 617 "guard grade >= passing_threshold;\nco:validate()" "SansSerif" 0 12 0 REF 39 
            CH.ifa.draw.standard.OffsetLocator 120 26 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 22 80 945 24 24 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 23 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 115 945 "t_SBT_Mint" "SansSerif" 1 12 0 REF 46 
            CH.ifa.draw.standard.OffsetLocator 55 -4 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 24 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 12 967 ":sbt_mint(issuerDID,studentDID,credentialData);\nco:sbt_mint(issuerDID,studentDID,credentialData);\nw:sbt_mint(this,issuerDID,studentDID,credentialData)" "SansSerif" 0 12 0 REF 46 
            CH.ifa.draw.standard.OffsetLocator 67 34 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 25 80 1295 24 24 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 26 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 115 1295 "t_SBT_Accept" "SansSerif" 1 12 0 REF 53 
            CH.ifa.draw.standard.OffsetLocator 63 -4 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 27 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 112 1317 ":sbt_accept(studentSignature);\nguard currentTime < expiryDate;\nco:sbt_accept(studentSignature,issuerSignature);\nl:anchor_request(this)" "SansSerif" 0 12 0 REF 53 
            CH.ifa.draw.standard.OffsetLocator 110 42 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 28 1080 1295 24 24 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 29 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1115 1295 "t_SBT_Reject" "SansSerif" 1 12 0 REF 60 
            CH.ifa.draw.standard.OffsetLocator 61 -4 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 30 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1068 1317 ":sbt_reject(studentSignature);\nco:sbt_reject(studentSignature,issuerSignature)" "SansSerif" 0 12 0 REF 60 
            CH.ifa.draw.standard.OffsetLocator 62 26 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 31 2080 1295 24 24 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 32 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 2115 1295 "t_SBT_Cancel" "SansSerif" 1 12 0 REF 67 
            CH.ifa.draw.standard.OffsetLocator 63 -4 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 33 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 2071 1317 "co:sbt_cancel(issuerSignature);\ns:abort(\"CANCELLED\");\nw:abort(\"CANCELLED\")" "SansSerif" 0 12 0 REF 67 
            CH.ifa.draw.standard.OffsetLocator 66 34 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 34 3080 1295 24 24 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 35 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 3115 1295 "t_SBT_Expire" "SansSerif" 1 12 0 REF 74 
            CH.ifa.draw.standard.OffsetLocator 61 -4 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 36 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 3115 1317 "guard currentTime >= expiryDate;\nco:expire(issuerSignature);\ns:abort(\"EXPIRED\");\nw:abort(\"EXPIRED\")" "SansSerif" 0 12 0 REF 74 
            CH.ifa.draw.standard.OffsetLocator 113 42 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 37 80 1645 24 24 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 38 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 115 1645 "t_Agg_Ingest" "SansSerif" 1 12 0 REF 81 
            CH.ifa.draw.standard.OffsetLocator 60 -4 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 39 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 67 1667 "co:update_profile(holderDID,vpData);\nh:update_profile(holderDID,vpData)" "SansSerif" 0 12 0 REF 81 
            CH.ifa.draw.standard.OffsetLocator 76 26 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 40 2 92 94 92 245 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 32   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 41 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 -93 153 "[issuerDID,studentDID,credentialData,issuerSignature,holderDID,vpData]" "SansSerif" 0 12 0 REF 88 
            CH.ifa.draw.standard.OffsetLocator 15 -8 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 42 2 92 269 92 421 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 32  
            CH.ifa.draw.figures.ChopEllipseConnector REF 8   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 43 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 -95 329 "[s,co,w,l,h,grade,passing_threshold,currentTime,expiryDate,issuerDID,studentDID,credentialData,issuerSignature,holderDID,vpData]" "SansSerif" 0 12 0 REF 95 
            CH.ifa.draw.standard.OffsetLocator 176 -8 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 44 2 92 444 92 595 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 8  
            CH.ifa.draw.standard.ChopBoxConnector REF 39   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 45 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 -95 503 "[s,co,w,l,h,grade,passing_threshold,currentTime,expiryDate,issuerDID,studentDID,credentialData,issuerSignature,holderDID,vpData]" "SansSerif" 0 12 0 REF 102 
            CH.ifa.draw.standard.OffsetLocator 176 -8 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 46 2 92 619 92 771 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 39  
            CH.ifa.draw.figures.ChopEllipseConnector REF 12   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 47 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 -95 679 "[s,co,w,l,h,grade,passing_threshold,currentTime,expiryDate,issuerDID,studentDID,credentialData,issuerSignature,holderDID,vpData]" "SansSerif" 0 12 0 REF 109 
            CH.ifa.draw.standard.OffsetLocator 176 -8 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 48 2 92 794 92 945 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 12  
            CH.ifa.draw.standard.ChopBoxConnector REF 46   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 49 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 -95 853 "[s,co,w,l,h,grade,passing_threshold,currentTime,expiryDate,issuerDID,studentDID,credentialData,issuerSignature,holderDID,vpData]" "SansSerif" 0 12 0 REF 116 
            CH.ifa.draw.standard.OffsetLocator 176 -8 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 50 2 92 969 92 1121 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 46  
            CH.ifa.draw.figures.ChopEllipseConnector REF 16   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 51 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 -95 1029 "[s,co,w,l,h,grade,passing_threshold,currentTime,expiryDate,issuerDID,studentDID,credentialData,issuerSignature,holderDID,vpData]" "SansSerif" 0 12 0 REF 123 
            CH.ifa.draw.standard.OffsetLocator 176 -8 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 52 2 92 1144 92 1295 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 16  
            CH.ifa.draw.standard.ChopBoxConnector REF 53   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 53 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 -95 1203 "[s,co,w,l,h,grade,passing_threshold,currentTime,expiryDate,issuerDID,studentDID,credentialData,issuerSignature,holderDID,vpData]" "SansSerif" 0 12 0 REF 130 
            CH.ifa.draw.standard.OffsetLocator 176 -8 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 54 2 104 1300 2203 118 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 53  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 72 2200 100 24 24 NULL    
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 55 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 966 693 "[s,co,w,l,h,grade,passing_threshold,currentTime,expiryDate,issuerDID,studentDID,credentialData,issuerSignature,holderDID,vpData]" "SansSerif" 0 12 0 REF 137 
            CH.ifa.draw.standard.OffsetLocator 176 -8 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 56 2 104 1134 1080 1304 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 16  
            CH.ifa.draw.standard.ChopBoxConnector REF 60   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 57 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 405 1203 "[s,co,w,l,h,grade,passing_threshold,currentTime,expiryDate,issuerDID,studentDID,credentialData,issuerSignature,holderDID,vpData]" "SansSerif" 0 12 0 REF 145 
            CH.ifa.draw.standard.OffsetLocator 176 -8 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 58 2 1092 1319 1092 1471 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 60  
            CH.ifa.draw.figures.ChopEllipseConnector REF 28   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 59 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 905 1379 "[s,co,w,l,h,grade,passing_threshold,currentTime,expiryDate,issuerDID,studentDID,credentialData,issuerSignature,holderDID,vpData,\"HOLDER_REJECTED\"]" "SansSerif" 0 12 0 REF 152 
            CH.ifa.draw.standard.OffsetLocator 242 -8 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 60 2 104 1133 2080 1305 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 16  
            CH.ifa.draw.standard.ChopBoxConnector REF 67   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 61 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 905 1203 "[s,co,w,l,h,grade,passing_threshold,currentTime,expiryDate,issuerDID,studentDID,credentialData,issuerSignature,holderDID,vpData]" "SansSerif" 0 12 0 REF 159 
            CH.ifa.draw.standard.OffsetLocator 176 -8 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 62 2 2080 1309 1104 1481 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 67  
            CH.ifa.draw.figures.ChopEllipseConnector REF 28   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 63 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1405 1379 "[s,co,w,l,h,grade,passing_threshold,currentTime,expiryDate,issuerDID,studentDID,credentialData,issuerSignature,holderDID,vpData,\"CANCELLED\"]" "SansSerif" 0 12 0 REF 166 
            CH.ifa.draw.standard.OffsetLocator 218 -8 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 64 2 104 1133 3080 1306 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 16  
            CH.ifa.draw.standard.ChopBoxConnector REF 74   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 65 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1405 1203 "[s,co,w,l,h,grade,passing_threshold,currentTime,expiryDate,issuerDID,studentDID,credentialData,issuerSignature,holderDID,vpData]" "SansSerif" 0 12 0 REF 173 
            CH.ifa.draw.standard.OffsetLocator 176 -8 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 66 2 3080 1308 1104 1482 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 74  
            CH.ifa.draw.figures.ChopEllipseConnector REF 28   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 67 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1905 1379 "[s,co,w,l,h,grade,passing_threshold,currentTime,expiryDate,issuerDID,studentDID,credentialData,issuerSignature,holderDID,vpData,\"EXPIRED\"]" "SansSerif" 0 12 0 REF 180 
            CH.ifa.draw.standard.OffsetLocator 207 -8 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 68 2 92 1494 92 1645 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 20  
            CH.ifa.draw.standard.ChopBoxConnector REF 81   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 69 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 -95 1553 "[s,co,w,l,h,grade,passing_threshold,currentTime,expiryDate,issuerDID,studentDID,credentialData,issuerSignature,holderDID,vpData]" "SansSerif" 0 12 0 REF 187 
            CH.ifa.draw.standard.OffsetLocator 176 -8 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 70 2 92 1669 92 1821 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 81  
            CH.ifa.draw.figures.ChopEllipseConnector REF 24   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 71 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 -95 1729 "[s,co,w,l,h,grade,passing_threshold,currentTime,expiryDate,issuerDID,studentDID,credentialData,issuerSignature,holderDID,vpData]" "SansSerif" 0 12 0 REF 194 
            CH.ifa.draw.standard.OffsetLocator 176 -8 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  REF 141 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 73 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 2235 100 "p_AwaitingAnchor" "SansSerif" 1 12 0 REF 141 
            CH.ifa.draw.standard.OffsetLocator 75 -4 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 74 2200 450 24 24 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 75 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 2235 450 "t_DenyInvalidSignature" "SansSerif" 1 12 0 REF 204 
            CH.ifa.draw.standard.OffsetLocator 88 -4 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 76 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 2235 472 ":deny(providedSignature);\nco:deny(providedSignature,issuerSignature)" "SansSerif" 0 12 0 REF 204 
            CH.ifa.draw.standard.OffsetLocator 98 26 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 77 2200 800 24 24 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 78 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 2235 800 "t_DenyInvalidIssuerSignature" "SansSerif" 1 12 0 REF 211 
            CH.ifa.draw.standard.OffsetLocator 106 -4 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 79 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 2235 822 "co:deny_issuer(issuerSignature);\ns:abort(\"INVALID_ISSUER_SIGNATURE\");\nw:abort(\"INVALID_ISSUER_SIGNATURE\")" "SansSerif" 0 12 0 REF 211 
            CH.ifa.draw.standard.OffsetLocator 138 34 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 80 2200 1150 24 24 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 81 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 2235 1150 "t_AnchorConfirmed" "SansSerif" 1 12 0 REF 218 
            CH.ifa.draw.standard.OffsetLocator 78 -4 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 82 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 2235 1172 ":anchor_confirm();\nco:anchor_confirm();\ns:anchor_confirm();\nw:anchor_confirm()" "SansSerif" 0 12 0 REF 218 
            CH.ifa.draw.standard.OffsetLocator 79 42 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 83 2200 1500 24 24 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 84 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 2235 1500 "t_LedgerFailed" "SansSerif" 1 12 0 REF 225 
            CH.ifa.draw.standard.OffsetLocator 65 -4 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 85 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 2235 1522 ":ledger_failed();\nco:ledger_failed();\ns:abort(\"LEDGER_REJECTED\");\nw:abort(\"LEDGER_REJECTED\")" "SansSerif" 0 12 0 REF 225 
            CH.ifa.draw.standard.OffsetLocator 112 42 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 86 2 103 1129 2200 465 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 16  
            CH.ifa.draw.standard.ChopBoxConnector REF 204   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 87 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 138 487 "[s,co,w,l,h,grade,passing_threshold,currentTime,expiryDate,issuerDID,studentDID,credentialData,issuerSignature,holderDID,vpData]" "SansSerif" 0 12 0 REF 232 
            CH.ifa.draw.standard.OffsetLocator -650 -302 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 88 2 2200 472 1101 1475 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 204  
            CH.ifa.draw.figures.ChopEllipseConnector REF 28   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 89 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1136 494 "[s,co,w,l,h,grade,passing_threshold,currentTime,expiryDate,issuerDID,studentDID,credentialData,issuerSignature,holderDID,vpData,\"INVALID_SIGNATURE\"]" "SansSerif" 0 12 0 REF 239 
            CH.ifa.draw.standard.OffsetLocator -85 -471 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 90 2 104 1131 2200 813 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 16  
            CH.ifa.draw.standard.ChopBoxConnector REF 211   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 91 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 139 835 "[s,co,w,l,h,grade,passing_threshold,currentTime,expiryDate,issuerDID,studentDID,credentialData,issuerSignature,holderDID,vpData]" "SansSerif" 0 12 0 REF 246 
            CH.ifa.draw.standard.OffsetLocator -650 -129 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 92 2 2200 819 1102 1477 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 211  
            CH.ifa.draw.figures.ChopEllipseConnector REF 28   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 93 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1137 841 "[s,co,w,l,h,grade,passing_threshold,currentTime,expiryDate,issuerDID,studentDID,credentialData,issuerSignature,holderDID,vpData,\"INVALID_ISSUER_SIGNATURE\"]" "SansSerif" 0 12 0 REF 253 
            CH.ifa.draw.standard.OffsetLocator -59 -299 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 94 2 2212 124 2212 1150 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 141  
            CH.ifa.draw.standard.ChopBoxConnector REF 218   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 95 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 2247 146 "[s,co,w,l,h,grade,passing_threshold,currentTime,expiryDate,issuerDID,studentDID,credentialData,issuerSignature,holderDID,vpData]" "SansSerif" 0 12 0 REF 260 
            CH.ifa.draw.standard.OffsetLocator 398 -483 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 96 2 2200 1163 104 1481 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 218  
            CH.ifa.draw.figures.ChopEllipseConnector REF 20   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 97 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 139 1185 "[s,co,w,l,h,grade,passing_threshold,currentTime,expiryDate,issuerDID,studentDID,credentialData,issuerSignature,holderDID,vpData]" "SansSerif" 0 12 0 REF 267 
            CH.ifa.draw.standard.OffsetLocator -650 -129 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 98 2 2212 124 2212 1500 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 141  
            CH.ifa.draw.standard.ChopBoxConnector REF 225   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 99 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 2247 146 "[s,co,w,l,h,grade,passing_threshold,currentTime,expiryDate,issuerDID,studentDID,credentialData,issuerSignature,holderDID,vpData]" "SansSerif" 0 12 0 REF 274 
            CH.ifa.draw.standard.OffsetLocator 398 -658 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 100 2 2200 1511 1104 1482 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 225  
            CH.ifa.draw.figures.ChopEllipseConnector REF 28   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 101 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1139 1504 "[s,co,w,l,h,grade,passing_threshold,currentTime,expiryDate,issuerDID,studentDID,credentialData,issuerSignature,holderDID,vpData,\"LEDGER_REJECTED\"]" "SansSerif" 0 12 0 REF 281 
            CH.ifa.draw.standard.OffsetLocator -84 16 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  NULL  