12 
    de.renew.gui.CPNDrawing 105 
        de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 1 80 70 24 24 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 2 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 115 70 "p_Submitted" "SansSerif" 1 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator 59 -4 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 3 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 -248 92 "[\"did:example:issuer1\",\"did:example:student1\",\"credential-001\",\"student-signature\",\"issuer-signature\",\"did:example:student1\",\"vp-001\"]" "SansSerif" 0 12 0 REF 1 
            CH.ifa.draw.standard.OffsetLocator 26 18 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 4 80 420 24 24 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 5 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 115 420 "p_UnderReview" "SansSerif" 1 12 0 REF 8 
            CH.ifa.draw.standard.OffsetLocator 67 -4 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 6 80 770 24 24 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 7 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 115 770 "p_Validated" "SansSerif" 1 12 0 REF 12 
            CH.ifa.draw.standard.OffsetLocator 56 -4 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 8 80 1120 24 24 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 9 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 115 1120 "p_PendingAccept" "SansSerif" 1 12 0 REF 16 
            CH.ifa.draw.standard.OffsetLocator 73 -4 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 10 80 1470 24 24 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 11 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 115 1470 "p_Anchored" "SansSerif" 1 12 0 REF 20 
            CH.ifa.draw.standard.OffsetLocator 57 -4 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 12 1080 1470 24 24 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 13 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1115 1470 "p_Rejected" "SansSerif" 1 12 0 REF 24 
            CH.ifa.draw.standard.OffsetLocator 55 -4 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 14 2080 1470 24 24 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 15 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 2115 1470 "p_Cancelled" "SansSerif" 1 12 0 REF 28 
            CH.ifa.draw.standard.OffsetLocator 58 -4 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 16 3080 1470 24 24 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 17 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 3115 1470 "p_Expired" "SansSerif" 1 12 0 REF 32 
            CH.ifa.draw.standard.OffsetLocator 51 -4 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 18 80 1820 24 24 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 19 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 115 1820 "p_Aggregated" "SansSerif" 1 12 0 REF 36 
            CH.ifa.draw.standard.OffsetLocator 63 -4 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 20 80 245 24 24 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 21 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 115 245 "t_StartReview" "SansSerif" 1 12 0 REF 40 
            CH.ifa.draw.standard.OffsetLocator 63 -4 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 22 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 115 267 ":evaluate(grade,passing_threshold,currentTime,expiryDate)" "SansSerif" 0 12 0 REF 40 
            CH.ifa.draw.standard.OffsetLocator 185 18 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 23 80 595 24 24 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 24 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 115 595 "t_Validate" "SansSerif" 1 12 0 REF 47 
            CH.ifa.draw.standard.OffsetLocator 51 -4 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 25 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 115 617 ":validate();\nguard grade >= passing_threshold" "SansSerif" 0 12 0 REF 47 
            CH.ifa.draw.standard.OffsetLocator 118 26 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 26 80 945 24 24 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 27 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 115 945 "t_Mint" "SansSerif" 1 12 0 REF 54 
            CH.ifa.draw.standard.OffsetLocator 40 -4 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 28 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 13 967 ":sbt_mint(issuerDID,studentDID,credentialData)" "SansSerif" 0 12 0 REF 54 
            CH.ifa.draw.standard.OffsetLocator 52 18 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 29 80 1295 24 24 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 30 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 115 1295 "t_Accept" "SansSerif" 1 12 0 REF 61 
            CH.ifa.draw.standard.OffsetLocator 48 -4 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 31 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 115 1317 ":sbt_accept(studentSignature,issuerSignature);\nguard currentTime < expiryDate" "SansSerif" 0 12 0 REF 61 
            CH.ifa.draw.standard.OffsetLocator 108 26 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 32 1080 1295 24 24 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 33 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1115 1295 "t_Reject" "SansSerif" 1 12 0 REF 68 
            CH.ifa.draw.standard.OffsetLocator 46 -4 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 34 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1068 1317 ":sbt_reject(studentSignature,issuerSignature)" "SansSerif" 0 12 0 REF 68 
            CH.ifa.draw.standard.OffsetLocator 55 18 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 35 2080 1295 24 24 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 36 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 2115 1295 "t_Cancel" "SansSerif" 1 12 0 REF 75 
            CH.ifa.draw.standard.OffsetLocator 48 -4 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 37 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 2071 1317 ":sbt_cancel(issuerSignature)" "SansSerif" 0 12 0 REF 75 
            CH.ifa.draw.standard.OffsetLocator 58 18 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 38 3080 1295 24 24 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 39 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 3115 1295 "t_Expire" "SansSerif" 1 12 0 REF 82 
            CH.ifa.draw.standard.OffsetLocator 46 -4 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 40 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 3115 1317 ":expire(issuerSignature);\nguard currentTime >= expiryDate" "SansSerif" 0 12 0 REF 82 
            CH.ifa.draw.standard.OffsetLocator 112 26 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 41 80 1645 24 24 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 42 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 115 1645 "t_Aggregate" "SansSerif" 1 12 0 REF 89 
            CH.ifa.draw.standard.OffsetLocator 58 -4 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 43 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 67 1667 ":update_profile(holderDID,vpData)" "SansSerif" 0 12 0 REF 89 
            CH.ifa.draw.standard.OffsetLocator 68 18 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 44 2 92 94 92 245 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 1  
            CH.ifa.draw.standard.ChopBoxConnector REF 40   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 45 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 -142 153 "[issuerDID,studentDID,credentialData,studentSignature,issuerSignature,holderDID,vpData]" "SansSerif" 0 12 0 REF 96 
            CH.ifa.draw.standard.OffsetLocator 15 -8 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 46 2 92 269 92 421 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 40  
            CH.ifa.draw.figures.ChopEllipseConnector REF 8   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 47 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 -143 329 "[grade,passing_threshold,currentTime,expiryDate,issuerDID,studentDID,credentialData,studentSignature,issuerSignature,holderDID,vpData]" "SansSerif" 0 12 0 REF 103 
            CH.ifa.draw.standard.OffsetLocator 149 -8 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 48 2 92 444 92 595 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 8  
            CH.ifa.draw.standard.ChopBoxConnector REF 47   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 49 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 -143 503 "[grade,passing_threshold,currentTime,expiryDate,issuerDID,studentDID,credentialData,studentSignature,issuerSignature,holderDID,vpData]" "SansSerif" 0 12 0 REF 110 
            CH.ifa.draw.standard.OffsetLocator 149 -8 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 50 2 92 619 92 771 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 47  
            CH.ifa.draw.figures.ChopEllipseConnector REF 12   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 51 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 -143 679 "[grade,passing_threshold,currentTime,expiryDate,issuerDID,studentDID,credentialData,studentSignature,issuerSignature,holderDID,vpData]" "SansSerif" 0 12 0 REF 117 
            CH.ifa.draw.standard.OffsetLocator 149 -8 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 52 2 92 794 92 945 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 12  
            CH.ifa.draw.standard.ChopBoxConnector REF 54   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 53 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 -143 853 "[grade,passing_threshold,currentTime,expiryDate,issuerDID,studentDID,credentialData,studentSignature,issuerSignature,holderDID,vpData]" "SansSerif" 0 12 0 REF 124 
            CH.ifa.draw.standard.OffsetLocator 149 -8 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 54 2 92 969 92 1121 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 54  
            CH.ifa.draw.figures.ChopEllipseConnector REF 16   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 55 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 -143 1029 "[grade,passing_threshold,currentTime,expiryDate,issuerDID,studentDID,credentialData,studentSignature,issuerSignature,holderDID,vpData]" "SansSerif" 0 12 0 REF 131 
            CH.ifa.draw.standard.OffsetLocator 149 -8 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 56 2 92 1144 92 1295 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 16  
            CH.ifa.draw.standard.ChopBoxConnector REF 61   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 57 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 -143 1203 "[grade,passing_threshold,currentTime,expiryDate,issuerDID,studentDID,credentialData,studentSignature,issuerSignature,holderDID,vpData]" "SansSerif" 0 12 0 REF 138 
            CH.ifa.draw.standard.OffsetLocator 149 -8 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 58 2 104 1300 2203 118 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 61  
            CH.ifa.draw.figures.ChopEllipseConnector 
                de.renew.gui.PlaceFigure "attributes" "attributes" 1 "FigureWithID" "Int" 76 2200 100 24 24 NULL    
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 59 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 918 693 "[grade,passing_threshold,currentTime,expiryDate,issuerDID,studentDID,credentialData,studentSignature,issuerSignature,holderDID,vpData]" "SansSerif" 0 12 0 REF 145 
            CH.ifa.draw.standard.OffsetLocator 149 -8 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 60 2 104 1134 1080 1304 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 16  
            CH.ifa.draw.standard.ChopBoxConnector REF 68   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 61 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 357 1203 "[grade,passing_threshold,currentTime,expiryDate,issuerDID,studentDID,credentialData,studentSignature,issuerSignature,holderDID,vpData]" "SansSerif" 0 12 0 REF 153 
            CH.ifa.draw.standard.OffsetLocator 149 -8 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 62 2 1092 1319 1092 1471 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 68  
            CH.ifa.draw.figures.ChopEllipseConnector REF 24   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 63 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 857 1379 "[grade,passing_threshold,currentTime,expiryDate,issuerDID,studentDID,credentialData,studentSignature,issuerSignature,holderDID,vpData,\"HOLDER_REJECTED\"]" "SansSerif" 0 12 0 REF 160 
            CH.ifa.draw.standard.OffsetLocator 216 -8 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 64 2 104 1133 2080 1305 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 16  
            CH.ifa.draw.standard.ChopBoxConnector REF 75   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 65 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 857 1203 "[grade,passing_threshold,currentTime,expiryDate,issuerDID,studentDID,credentialData,studentSignature,issuerSignature,holderDID,vpData]" "SansSerif" 0 12 0 REF 167 
            CH.ifa.draw.standard.OffsetLocator 149 -8 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 66 2 2092 1319 2092 1471 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 75  
            CH.ifa.draw.figures.ChopEllipseConnector REF 28   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 67 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1857 1379 "[grade,passing_threshold,currentTime,expiryDate,issuerDID,studentDID,credentialData,studentSignature,issuerSignature,holderDID,vpData,\"CANCELLED\"]" "SansSerif" 0 12 0 REF 174 
            CH.ifa.draw.standard.OffsetLocator 191 -8 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 68 2 104 1133 3080 1306 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 16  
            CH.ifa.draw.standard.ChopBoxConnector REF 82   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 69 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1357 1203 "[grade,passing_threshold,currentTime,expiryDate,issuerDID,studentDID,credentialData,studentSignature,issuerSignature,holderDID,vpData]" "SansSerif" 0 12 0 REF 181 
            CH.ifa.draw.standard.OffsetLocator 149 -8 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 70 2 3092 1319 3092 1471 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 82  
            CH.ifa.draw.figures.ChopEllipseConnector REF 32   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 71 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 2857 1379 "[grade,passing_threshold,currentTime,expiryDate,issuerDID,studentDID,credentialData,studentSignature,issuerSignature,holderDID,vpData,\"EXPIRED\"]" "SansSerif" 0 12 0 REF 188 
            CH.ifa.draw.standard.OffsetLocator 181 -8 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 72 2 92 1494 92 1645 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 20  
            CH.ifa.draw.standard.ChopBoxConnector REF 89   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 73 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 -143 1553 "[grade,passing_threshold,currentTime,expiryDate,issuerDID,studentDID,credentialData,studentSignature,issuerSignature,holderDID,vpData]" "SansSerif" 0 12 0 REF 195 
            CH.ifa.draw.standard.OffsetLocator 149 -8 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 74 2 92 1669 92 1821 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 89  
            CH.ifa.draw.figures.ChopEllipseConnector REF 36   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 75 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 -143 1729 "[grade,passing_threshold,currentTime,expiryDate,issuerDID,studentDID,credentialData,studentSignature,issuerSignature,holderDID,vpData]" "SansSerif" 0 12 0 REF 202 
            CH.ifa.draw.standard.OffsetLocator 149 -8 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  REF 149 
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 77 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 2235 100 "p_AwaitingAnchor" "SansSerif" 1 12 0 REF 149 
            CH.ifa.draw.standard.OffsetLocator 75 -4 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 78 2200 450 24 24 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 79 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 2235 450 "t_DenyInvalidSignature" "SansSerif" 1 12 0 REF 212 
            CH.ifa.draw.standard.OffsetLocator 88 -4 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 80 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 2235 472 ":deny(providedSignature,issuerSignature);\nguard !providedSignature.equals(studentSignature)" "SansSerif" 0 12 0 REF 212 
            CH.ifa.draw.standard.OffsetLocator 163 26 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 81 2200 800 24 24 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 82 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 2235 800 "t_DenyInvalidIssuerSignature" "SansSerif" 1 12 0 REF 219 
            CH.ifa.draw.standard.OffsetLocator 106 -4 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 83 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 2235 822 ":deny_issuer(providedIssuerSignature);\nguard !providedIssuerSignature.equals(issuerSignature)" "SansSerif" 0 12 0 REF 219 
            CH.ifa.draw.standard.OffsetLocator 178 26 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 84 2200 1150 24 24 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 85 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 2235 1150 "t_AnchorConfirmed" "SansSerif" 1 12 0 REF 226 
            CH.ifa.draw.standard.OffsetLocator 78 -4 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 86 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 2235 1172 ":anchor_confirm()" "SansSerif" 0 12 0 REF 226 
            CH.ifa.draw.standard.OffsetLocator 71 18 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.TransitionFigure "attributes" "attributes" 1 "FigureWithID" "Int" 87 2200 1500 24 24 NULL  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 88 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 2235 1500 "t_LedgerFailed" "SansSerif" 1 12 0 REF 233 
            CH.ifa.draw.standard.OffsetLocator 65 -4 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   2  
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 89 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 2235 1522 ":ledger_failed()" "SansSerif" 0 12 0 REF 233 
            CH.ifa.draw.standard.OffsetLocator 64 18 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 90 2 103 1129 2200 465 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 16  
            CH.ifa.draw.standard.ChopBoxConnector REF 212   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 91 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 138 487 "[grade,passing_threshold,currentTime,expiryDate,issuerDID,studentDID,credentialData,studentSignature,issuerSignature,holderDID,vpData]" "SansSerif" 0 12 0 REF 240 
            CH.ifa.draw.standard.OffsetLocator -629 -302 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 92 2 2200 472 1101 1475 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 212  
            CH.ifa.draw.figures.ChopEllipseConnector REF 24   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 93 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1136 494 "[grade,passing_threshold,currentTime,expiryDate,issuerDID,studentDID,credentialData,studentSignature,issuerSignature,holderDID,vpData,\"INVALID_SIGNATURE\"]" "SansSerif" 0 12 0 REF 247 
            CH.ifa.draw.standard.OffsetLocator -64 -471 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 94 2 104 1131 2200 813 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 16  
            CH.ifa.draw.standard.ChopBoxConnector REF 219   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 95 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 139 835 "[grade,passing_threshold,currentTime,expiryDate,issuerDID,studentDID,credentialData,studentSignature,issuerSignature,holderDID,vpData]" "SansSerif" 0 12 0 REF 254 
            CH.ifa.draw.standard.OffsetLocator -629 -129 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 96 2 2200 819 1102 1477 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 219  
            CH.ifa.draw.figures.ChopEllipseConnector REF 24   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 97 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1137 841 "[grade,passing_threshold,currentTime,expiryDate,issuerDID,studentDID,credentialData,studentSignature,issuerSignature,holderDID,vpData,\"INVALID_ISSUER_SIGNATURE\"]" "SansSerif" 0 12 0 REF 261 
            CH.ifa.draw.standard.OffsetLocator -38 -299 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 98 2 2212 124 2212 1150 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 149  
            CH.ifa.draw.standard.ChopBoxConnector REF 226   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 99 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 2247 146 "[grade,passing_threshold,currentTime,expiryDate,issuerDID,studentDID,credentialData,studentSignature,issuerSignature,holderDID,vpData]" "SansSerif" 0 12 0 REF 268 
            CH.ifa.draw.standard.OffsetLocator 419 -483 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 100 2 2200 1163 104 1481 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 226  
            CH.ifa.draw.figures.ChopEllipseConnector REF 20   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 101 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 139 1185 "[grade,passing_threshold,currentTime,expiryDate,issuerDID,studentDID,credentialData,studentSignature,issuerSignature,holderDID,vpData]" "SansSerif" 0 12 0 REF 275 
            CH.ifa.draw.standard.OffsetLocator -629 -129 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 102 2 2212 124 2212 1500 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.figures.ChopEllipseConnector REF 149  
            CH.ifa.draw.standard.ChopBoxConnector REF 233   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 103 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 2247 146 "[grade,passing_threshold,currentTime,expiryDate,issuerDID,studentDID,credentialData,studentSignature,issuerSignature,holderDID,vpData]" "SansSerif" 0 12 0 REF 282 
            CH.ifa.draw.standard.OffsetLocator 419 -658 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  
        de.renew.gui.ArcConnection "attributes" "attributes" 1 "FigureWithID" "Int" 104 2 2200 1511 1104 1482 NULL 
            CH.ifa.draw.figures.ArrowTip 0.4 8.0 8.0 1  "CH.ifa.draw.figures.ArrowTip" 
            CH.ifa.draw.standard.ChopBoxConnector REF 233  
            CH.ifa.draw.figures.ChopEllipseConnector REF 24   
        de.renew.gui.CPNTextFigure "attributes" "attributes" 4 "TextAlignment" "Int" 1 "FigureWithID" "Int" 105 "FrameColor" "Color" 255 199 158 255 "FillColor" "Color" 255 199 158 255 1139 1504 "[grade,passing_threshold,currentTime,expiryDate,issuerDID,studentDID,credentialData,studentSignature,issuerSignature,holderDID,vpData,\"LEDGER_REJECTED\"]" "SansSerif" 0 12 0 REF 289 
            CH.ifa.draw.standard.OffsetLocator -63 16 
                CH.ifa.draw.standard.RelativeLocator 0.5 0.5   1  NULL  